In [ ]:
import numpy as np
import pandas as pd
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [6]:
data = pd.read_csv('/content/sample_data/placement.csv')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   cgpa          100 non-null    float64
 1   resume_score  100 non-null    float64
 2   placed        100 non-null    int64  
dtypes: float64(2), int64(1)
memory usage: 2.5 KB


In [7]:
#Input and output
x = data[['cgpa','resume_score']]
y = data['placed']

In [8]:
#Train Test split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [9]:
#model
model = Perceptron(max_iter=1000,random_state=42)
model.fit(x_train,y_train)

Perceptron(random_state=42)

In [10]:
#Prediction
y_pred = model.predict(x_test)
print("Prediction : ")
print(y_pred)

Prediction : 
[0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0]


In [11]:
#Evaluation
acc = accuracy_score(y_test,y_pred)
print("Accuracy Score : ",acc)
cm = confusion_matrix(y_test,y_pred)
print("Confusion Matrix : ",cm)
print("Classification Report : ")
print(classification_report(y_test,y_pred))

Accuracy Score :  0.55
Confusion Matrix :  [[8 0]
 [9 3]]
Classification Report : 
              precision    recall  f1-score   support

           0       0.47      1.00      0.64         8
           1       1.00      0.25      0.40        12

    accuracy                           0.55        20
   macro avg       0.74      0.62      0.52        20
weighted avg       0.79      0.55      0.50        20



In [12]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [14]:
#Dataset
data = pd.read_csv('/content/sample_data/seeds_data.csv')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 199 entries, 0 to 198
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Area             199 non-null    float64
 1   Perimeter        199 non-null    float64
 2   Compactness      199 non-null    float64
 3   Kernel.Length    199 non-null    float64
 4   Kernel.Width     199 non-null    float64
 5   Asymmetry.Coeff  199 non-null    float64
 6   Kernel.Groove    199 non-null    float64
 7   Type             199 non-null    int64  
dtypes: float64(7), int64(1)
memory usage: 12.6 KB


In [15]:
#Input and output
x = data.drop("Type",axis=1)
y = data['Type']

In [16]:
#Train Test split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [17]:
#model
model = Perceptron(max_iter=1000,random_state=42)
model.fit(x_train,y_train)

Perceptron(random_state=42)

In [18]:
#Prediction
y_pred = model.predict(x_test)
print("Prediction : ")
print(y_pred)

Prediction : 
[2 2 2 3 2 3 2 2 2 3 3 3 3 2 2 2 2 3 2 3 2 2 2 3 2 3 3 2 3 2 3 2 3 3 2 2 2
 2 2 2]


In [19]:
#Evaluation
acc = accuracy_score(y_test,y_pred)
print("Accuracy Score : ")
print(acc)
cm = confusion_matrix(y_test,y_pred)
print("Confusion Matrix : ")
print(cm)
print("Classification Report  : ")
print(classification_report(y_test,y_pred))

Accuracy Score : 
0.775
Confusion Matrix : 
[[ 0  6  3]
 [ 0 19  0]
 [ 0  0 12]]
Classification Report  : 
              precision    recall  f1-score   support

           1       0.00      0.00      0.00         9
           2       0.76      1.00      0.86        19
           3       0.80      1.00      0.89        12

    accuracy                           0.78        40
   macro avg       0.52      0.67      0.58        40
weighted avg       0.60      0.78      0.68        40



/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
